### ISSUE TITLE
Drag-and-drop to playlist broken on v10

### ISSUE THREAD

**Issue by Gawdl3y** [SvenWerlen/moulinette-sounds#8]
When attempting to drag a sound from the Moulinette sound browser into a playlist in Foundry v10, the following errors are generated:
```
Error: PlaylistSound Model Validation Errors
[PlaylistSound.volume]: must be an increment of 0.01
[No packages detected]
    at SchemaField._validateType (commons.js:3636:15)
    at SchemaField.validate (commons.js:3363:37)
    at PlaylistSound.validate (commons.js:5016:35)
    at new DataModel (commons.js:4793:26)
    at new Document (commons.js:5332:3)
    at new BasePlaylistSound (commons.js:8947:3)
    at new ClientDocumentMixin (foundry.js:12999:5)
    at new PlaylistSound (foundry.js:20084:5)
    at ClientDatabaseBackend._preCreateDocumentArray (foundry.js:12401:15)
    at ClientDatabaseBackend._createEmbeddedDocuments (foundry.js:12364:33)
    at ClientDatabaseBackend.create (commons.js:6261:33)
    at async PlaylistSound.createDocuments (commons.js:5631:23)

PlaylistSound Model Validation Errors
[PlaylistSound.volume]: must be an increment of 0.01
[No packages detected]
```

**Comment by SvenWerlen** [comment]
Thank you for reporting this!
Fixed in `moulinette-sounds` `v-10.0.3`
